#!/bin/sh

#Default values
export ARTIFACTORY_HOME=/opt/artifactory
export ARTIFACTORY_USER=artifactory
#export JAVA_HOME=/opt/java/1.8.0

export TOMCAT_HOME=/opt/artifactory/tomcat
export ARTIFACTORY_PID=$ARTIFACTORY_HOME/run/artifactory.pid

#export JAVA_OPTIONS="-server -Xms512m -Xmx2g -Xss256k -XX:+UseG1GC -XX:OnOutOfMemoryError=\"kill -9 %p\""
#reduce the amount of memory it uses
export JAVA_OPTIONS="-server -Xms512m -Xmx1g -Xss256k -XX:+UseG1GC -XX:OnOutOfMemoryError=\"kill -9 %p\""
export JAVA_OPTIONS="$JAVA_OPTIONS -Djruby.compile.invokedynamic=false -Dfile.encoding=UTF8 -Dartdist=zip -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true -Djava.security.egd=file:/dev/./urandom"

# Timeout waiting for artifactory to start
# START_TMO=60
